version: '3.7'
services:
  dev:
    image: geiser/r-dev:latest
    container_name: rshinystatistic_dev
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/home/rstudio 
    ports:
      - "8787:8787"
  
